### ISSUE TITLE
Use theorem styles

### ISSUE THREAD

**Issue by jdutant** [jdutant/statement#3]
It is probably wiser to follow the LaTeX approach of using theorem styles. LaTeX defines three theorem styles (plain, definition and remark) that are typeset differently. This allows specifying a unique style for many theorems. 

Proposed addition to the object model:

```yaml
statement-filter:
  kinds:
     theorem: 
       - ...
       - style: plain
    ...
  styles:
     plain: [style specification]
```

The question is how the user provides the style specification: in a format-independent way (makes it difficult to provide a fine control of the margins or PDF-specific behaviour), or by format-specific code.
