### ISSUE TITLE
Changing label of theorem not working

### ISSUE THREAD

**Issue by neozhaoliang** [jdutant/statement#9]
Hi, Thank you for developing this filter, it helped me a lot. I'm having trouble with using my custom labels for the theorem environment.

Below is my metadata yaml config:

```yaml
statement-filter:
  kinds:
    theorem:
      - label: "定理"
      - counter: "theorem"
      - prefix: thm  # ref to theorem with `@thm:
    lemma:
      - label: "Lemma"
      - counter: "lemma"
      - prefix: lem
```

Here I changed the default label `Theorem` to `定理` (theorem in Mandarin).

In my markdown file, I tested it with an example:

```
::: theorem
Here is a test
:::
```

But I still got `Theorem`  (in HTML output) as the rendered label:

![image](https://github.com/dialoa/statement/assets/23307174/5de484fe-36c0-4324-932d-36236f7ec12b)

Also, the counter "lemma" seems not working as expected, it increases with the "theorem" counter:
![图片](https://github.com/dialoa/statement/assets/23307174/62dc8320-dfac-4619-b425-39b14db47aef)

May I ask what's wrong here?

**Comment by neozhaoliang** [comment]
Solved based on the tests/ examples. Btw, your README doc is outdated and should be updated.

**Comment by twsh** [comment]
For completeness, I think this is an example of metadata that works:

```
statement-kinds:
    theorem:
        label: "定理"
        counter: "theorem"
        prefix: thm  # ref to theorem with `@thm:
    lemma:
        label: "Lemma"
        counter: "lemma"
        prefix: lem
```
